# Number lines
add-highlighter global/ number-lines -relative

# Gets rid of awful clippy
set global ui_options ncurses_assistant=none

# Colorscheme
#colorscheme windows-subsystem

# Tab key inserts spaces to proper indentation level (not fixed width)
hook global InsertChar \t %{ try %{
    execute-keys -draft h %opt{indentwidth}@
} }

# Backspace key deindents
map global insert <backspace> ⌫
hook global InsertChar ⌫ %{ try %{
    execute-keys <backspace>
    try %{
        execute-keys -draft hGh <a-k>\A\h+\z<ret> <lt>
    } catch %{
        execute-keys <backspace>
    }
} }

# Tab key cycles completion menu
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}
